# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Monica Gerber
tagline:             ''
description:         'A blog about public health, data science, etc.'
url:                 http://monicagerber.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Monica Gerber
  url:               https://twitter.com/mwgerber
  email:             mwgerber@gmail.com

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
