# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Monica Gerber
tagline:             'Adventures in Epidemiology'
description:         'BUSPH `15. Learning how to bridge the gap between the classroom and real-world problems.'
url:                 http://monicagerber.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Monica Gerber
  url:               https://twitter.com/mwgerber
  email:             mwgerber@gmail.com


